version: "3"

services:
  stationdb:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - stationdb_data:/var/lib/postgresql/data
      - ./db/init-queries:/docker-entrypoint-initdb.d

  ciclo-py:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/data:/app/data
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      HOST: ${HOST}
      PORT: ${PORT}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
    depends_on: 
      - stationdb

volumes:
  stationdb_data:
