version: "3"

services:
  fastapi:
    build: api/
    depends_on:
      - postgres
    ports:
      - '8000:8000'

  postgres:
    image: pgrouting/pgrouting
    build: db/
    ports:
      - '5432:5432'